---
title: "ENVS-193DS_spring-2025_final"
format: html
editor: visual
---

github repo: https://github.com/emilyl-2324/ENVS-193DS_spring-2025_final.git 

```{r}
library(tidyverse)
library(janitor)
```

# Problem 1

## a. Transparent statistical methods (8 points)
*What statistical tests did your co-worker use? Clearly connect the test to the part that you are addressing (e.g. “In part 1, they used _______. In part 2, they used _______.”).*
In part 1, they used a person's r test, since the study is finding the correlation between two variables. In part 2, they used an anova test since the study is comparing the means of two or more groups (the test compares the mean nitrogen load from 5 different sources). 

## b. More information needed (8 points)
*The test in part 2 seems familiar to you, but you think there’s more that your co-worker needs to do to provide more context for the results. List 2 additional tests and/or pieces of information that should be included, and explain why those tests and/or pieces of information would add useful additional context.*

*Be specific and use variables and/or statistics from the example.*
One additional test is a test for normality, since ANOVA assumes the data is normally distributed. This can be done through a shapiro-wilk test for each of the sources of nitrogen load (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands). If test-statistics is close to 1, then the sample is normally distributed and if the sample doesn't equal 1, then the sample is not normally distributed.

Another test that should be done is the f-test, which tests for significance between groups, where the f-statistic is a ratio of two variances: the ms (mean square) among the group and the ms within the group. If the ms among groups is significantly larger than ms within groups, the f-stat is large and the null hypothesis should be rejected. 

possible tests: 
significance level. 
f-statistic. 
post hocs test.
effective size.

## c. Suggestions for rewriting (20 points)
*In 1-3 sentences, write new research statements to include relevant components from parts a-b and a full test summary in parentheses to be transparent about the statistical method.*

*Be sure that your rewritten statements clearly delineate the biological narrative from the statistical summary. See lecture and workshop for examples of writing.* 

*Note that your co-worker didn’t include any information about the test statistic, distribution, etc., and that you only know the p-value. For any part that you do not know, list that part with text. For example, you could write something like: “… r = correlation coefficient, p = 0.03, a = significance level …”*



